# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-09 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20171009_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='institution',
            new_name='institucion',
        ),
    ]
