# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-09 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20171009_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
