# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-09 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_auto_20171009_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
